### ISSUE TITLE
Unit tests for the interpreter

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#101]
## User Story
1. As a {developer}
2. I want {unit tests to run}
3. So that {I can be sure my changes don't break anything}

## User Acceptance Criteria
- [ ] Unit tests are available for interpreter
- [ ] Unit tests are ran automatically for PRs and merges to main

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
I think this issue should be addressed by the hard work of @f3l1x98, right?
