### ISSUE TITLE
Decide on what/how to open source

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#103]
## User Story
1. As a {developer}
2. I want {to decide what and how to open source}
3. So that {I can open source jayvee}

## User Acceptance Criteria
- [x] Decide what exactly to open source of jayvee
- [x] Decide how to open source it
  - [x] license
  - [x] move code into it's own organization or keep it in jvalue?
- [ ] Decision is documented in a RFC #102 

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
I think RFCs are there for changes on the language design, not the project setup. We open sourced, so can I close this issue?

**Comment by rhazn** [comment]
Agree here as well, when we wrote the task the understanding of RFCs was still a bit different 😅
