### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#105]
## User Story
1. As a {user}
2. I want {to have good documentation}
3. So that {I can get started with Jayvee}

## User Acceptance Criteria
- [x] Technical docs exist to explain the software architecture and repository structure to potential future contributors to the jayvee language
- [x] How to extend the Jayvee interpreter with new extensions docs exist for potential future contributors to the interpreter
- [x] RFC process for language changes is linked and explained in main readme.md
- [x] CONTRIBUTE.md 
  - [x] exists
  - [x] explains different forms of contribution (language RFCs, language implementation, interpreter extension)
  - [x] is linked from main readme
- [x] How to use docs exist to explain how to use Jayvee to build data pipeline models, how to run them locally and a reference to jvalue hub for future users of the language
  - can be an extension of the AMSE handout
  - linked in main readme.md

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
I believe this is kind of done?

**Comment by rhazn** [comment]
I agree, can be closed with #324 I think.
