### ISSUE TITLE
Open source Jayvee

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#106]
## User Acceptance Criteria
- [x] Jayvee repository is public 
- [x] There is an open source license
- [x] There is a CODE_OF_CONDUCT file #239 
- [x] There is a CONTRIBUTING file #240  
- [ ] Reuse badge added to README (links us on their page)

## Definitions of Done
- [x] A PR has been opened and accepted
- [x] All user acceptance criteria are met
- [x] All tests are passing

**Comment by georg-schwarz** [comment]
> Reuse badge added to README (links us on their page)

Will omit that as it adds the project on a list of reuse compliant projects. We should do that when we start advertising the project.

Issue can be closed?

**Comment by rhazn** [comment]
I agree 👏
