### ISSUE TITLE
Processing blocks with multiple Inputs

### ISSUE THREAD

**Issue by schlingling** [jvalue/jayvee#181]
Jayvee should process blocks with multiple inputs.

              Note that multiple outputs are already implemented, so for `ArchiveInterpreter` it should work out of the box. For multiple inputs, the execution logic in the interpreter needs to be modified. It is located in this method:

https://github.com/jvalue/jayvee/blob/fc9ffb80d78eee5276671a50ffd50a421217408d/apps/interpreter/src/interpreter.ts#L80-L84

After it has been implemented, the validation, that prevents multiple inputs, needs to be removed:

https://github.com/jvalue/jayvee/blob/fc9ffb80d78eee5276671a50ffd50a421217408d/libs/language-server/src/lib/validation/block-validator.ts#L236-L246

Let me know whether you need help with the implementation, we can do a pair programming session if you want.

_Originally posted by @felix-oq in https://github.com/jvalue/jayvee/pull/116#discussion_r1090374579_

**Comment by georg-schwarz** [comment]
Closed in favor of https://github.com/jvalue/jayvee/issues/512
