### ISSUE TITLE
[FEATURE] Publish library for parsing models

### ISSUE THREAD

**Issue by joluj** [jvalue/jayvee#204]
## User Story
1. As a {developer}
2. I want {to have an easy way to parse models}
3. So that {I can extract information without the need for the interpreter}

## User Acceptance Criteria
- [ ] function exported
- [ ] works in NodeJS and Browser

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
I think this should be solved with the introduction of the `interpreter-lib` package, right?
