### ISSUE TITLE
[FEATURE] Write clear install instructions for users

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#211]
## User Story
1. As a {user}
2. I want {good docs how to install the jayvee interpreter}
4. So that {I can install it}

## User Acceptance Criteria
- [x] Clear installation instructions for the jv interpreter are available
- [x] Installation instructions are in a separately linkable location, not inside main README.md so students have as little overhead as possible
- [x] Installation instructions clearly call out the need for node 17+
- [ ] Instructions link to a separate FAQ, mentioning the following error `structuredClone is not defined` as related to Node 17

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
FAQ still missing, will do that ASAP.
