### ISSUE TITLE
[FEATURE] Deal easier with renaming header names

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#214]
## User Story
1. As a {user}
2. I want {to be able to have an easier time renaming header names in files}
3. So that {I can parse them}

## User Acceptance Criteria
- [ ] a header name mapper/renamer block is available that allows to map multiple input names to output names to mass translate the headers
- [ ] a block is available that renames multiple headers/cells instead of chaining multiple cell writers (to rename the non-unique header values)

## Examples
- This example includes non-unique headers (so some need to be renamed) and german headers (that should be bulk translated) https://github.com/jvalue/amse-exercises/blob/main/exercise4.jv

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
Then extending the `CellWriter` block to always work on an array of cells would be the easiest option I guess. Optionally, we could introduce a `RowWriter` for syntactic sugar.
