### ISSUE TITLE
[BUG] npm package "jayvee-interpreter" does not exist under owner "jvalue"

### ISSUE THREAD

**Issue by schlingling** [jvalue/jayvee#306]
## Steps to reproduce
1. Run `npm i @jvalue/jayvee-interpreter`

## Description
- Expected: Installation of jayvee interpreter
- Actual:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/58326464/235360581-87bbef25-7932-45cf-8880-4a1030ef89f6.png">

Please update docs, if needed.

**Comment by felix-oq** [comment]
I think your npm is configured wrongly. In the command line, you can see that the URL points to `pkg.github.com` but instead it has to be `registry.npmjs.org`.

**Comment by schlingling** [comment]
> 

Thanks, after deleting my `.npmrc` the download works now.
