### ISSUE TITLE
[BUG] Mistake in RangeConstraint Documentation

### ISSUE THREAD

**Issue by nmarkert** [jvalue/jayvee#364]
## Steps to reproduce
1. Open https://jvalue.github.io/jayvee/docs/user/constraint-types/RangeConstraint
2. See Example 2

## Description
- It shows:
![image](https://github.com/jvalue/jayvee/assets/66016784/d943f895-94cb-42b8-8c6b-30bd9c179cdf)

- Mistake:
The description doesn't match with the code (as far as I understand the syntax correct)
Either the code has to be corrected:
```
constraint HundredScale oftype RangeConstraint {
  lowerBound: 0;
  lowerBoundInclusive: false;
  upperBound: 100;      
}
```
Or the description:
"A scale between **1** (excluded) and 100."

**Comment by georg-schwarz** [comment]
Nice catch! Thanks for the pointer ;-)
