### ISSUE TITLE
Correctly handle booleans in SQLite

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#368]
# When saving booleans to SQLite with Jayvee:
- pandas `read_sql_table` returns all as `true`
- VSCodes SQLite viewer plugin shows all as `true`
- DB Browser for SQLite Version 3.12.2 shows all correctly as `true` or `false` and the type as `boolean`

# When saving booleans to SQLite with Python:
- pandas `read_sql_table` returns all correctly as `true` or `false`
- VSCodes SQLite viewer plugin shows all correctly as `true` or `false`
- DB Browser for SQLite Version 3.12.2 shows all as `1` or `0` and the type as `BOOLEAN`

# Notes
- SQLite does not have a boolean storage class, it stores `1` and `0` but accepts `"TRUE"`/`"False"` as of version 3.23.0 (2018-04-02) (https://www.sqlite.org/datatype3.html)
- Jayvee writes boolean values to SQL as `"true"` or `"false"` (https://github.com/jvalue/jayvee/blob/4d7cf3680db0788c1d2be2a9eb4890012a1379d0/libs/execution/src/lib/types/valuetypes/visitors/sql-value-representation-visitor.ts#L20)

**Comment by rhazn** [comment]
I'd like to hear your thoughts @georg-schwarz but in general I'd suggest:

- separating SQLite and generic SQL visitors again
- saving booleans in SQLite as boolean value type with a value of integer literals `1`/`0` to be conform with even old SQLite versions

**Comment by georg-schwarz** [comment]
No objection from my side. I'd assume we will need to support some other sql dialects in the future as well. 

Maybe we can avoid some code duplication by inheritance (?)

**Comment by rhazn** [comment]
#373
