### ISSUE TITLE
[BUG] Floating point precision

### ISSUE THREAD

**Issue by derwehr** [jvalue/jayvee#380]
The following equations will return different results:

 **a)** `20 * 1.8 + 32` returns `65.300000000001`
 **b)** `20 * 9 / 5 + 32` returns `65.3`

## Steps to reproduce
1. run the jv program shown below
2. check the results in the `temperature.sqlite` file

```
transform CelsiusToFahrenheitA {
    from tempCelsius oftype decimal;
    to tempFahrenheit oftype decimal;

    tempFahrenheit: tempCelsius * 1.8 + 32;
}

transform CelsiusToFahrenheitB {
    from tempCelsius oftype decimal;
    to tempFahrenheit oftype decimal;

    tempFahrenheit: tempCelsius * 9/5 + 32;
}

pipeline testFloatTransforms {
    block extractor oftype HttpExtractor {
        url: "https://gist.githubusercontent.com/derwehr/f8886bc1db2fdaa22e7873c88a74bec7/raw/dc8976f4864d4d2eef416a0245f27aec64e56104/temperature.csv";
    }

    block textFileInterpreter oftype TextFileInterpreter {
    }

    block csvInterpreter oftype CSVInterpreter {
        delimiter: ";";
    }

    block tableInterpreter oftype TableInterpreter {
        header: false;
        columns: [
            "tempCelsius" oftype decimal,
            "tempFahrenheitA" oftype decimal,
            "tempFahrenheitB" oftype decimal
        ];
    }

    block celsiusToFahrenheitA oftype TableTransformer {
        inputColumn: "tempCelsius";
        outputColumn: "tempFahrenheitA";
        use: CelsiusToFahrenheitA;
    }

    block celsiusToFahrenheitB oftype TableTransformer {
        inputColumn: "tempCelsius";
        outputColumn: "tempFahrenheitB";
        use: CelsiusToFahrenheitB;
    }

    block loader oftype SQLiteLoader {
        table: "temperature";
        file: "temperature.sqlite";
    }

    extractor 
        -> textFileInterpreter
        -> csvInterpreter
        -> tableInterpreter
        -> celsiusToFahrenheitA
        -> celsiusToFahrenheitB
        -> loader;
}
```

## Description
- Expected:  all results should be `65.3`
- Actual: **a)** is `65.300000000001` **b)** is `65.3`

**Comment by georg-schwarz** [comment]
Thank you for your bug report!
Floating point operations always struggle with precision (I think the same is true for other languages).

#376 will introduce a well-defined support for rational numbers. Thus, closing this bug report in favor of #376.

**Comment by rhazn** [comment]
Interesting, I tried to reproduce the issue with your expressions but neither of them fails the feedback for me.

In any case, I updated the feedback rubric to compare the temperatures not by equality but just to check if they are close. This should reduce any floating point imprecision issues with it.

Thank you for bringing it to our attention!

**Comment by derwehr** [comment]
You're right, sorry. I was looking at the wrong run. Both of the transformers above worked. `tempCelsius * 1.8 + 32` was failing, but with your latest changes that works too now, thanks.
