### ISSUE TITLE
[FEATURE] Show error message when NodeJS version is not compatible

### ISSUE THREAD

**Issue by maanex** [jvalue/jayvee#387]
## User Story
1. I tried running a jv pipeline on a new setup where I freshly installed the interpreter.
2. Running this pipeline threw a weird error unrelated to the pipeline.
3. I spent several minutes to figure out that the error was a result of the system's NodeJS version being below 17.0.0
4. The console log only showed some internal javascript missing function error, no hint that the user needs to update their version.
5. A user friendly warning or error when running `jv` with an outdated NodeJS version would have helped a lot.

## User Acceptance Criteria
- [x] An error or warning is shown when running any jv command if the NodeJS version is below the required version

## Notes
This might be relevant: https://nodejs.org/api/process.html#processversion

## Definitions of Done
- [x] A PR has been opened and accepted
- [x] All user acceptance criteria are met
- [x] All tests are passing

**Comment by rhazn** [comment]
Thank you for the report, I agree that we should work on our messaging about the minimum required node version 👍 .
