### ISSUE TITLE
[FEATURE] HTTPExtractor should follow redirects

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#391]
## User Story
1. As a {user/persona}
2. I want {that the HTTPExtractor can download files from S3 buckets}
3. So that {I can use data in S3}

## User Acceptance Criteria
- [ ] A new optional property "followRedirects" exists for the HTTPExtractor block, by default it is true
- [ ] if followRedirects is true, HTTPExtractor follows redirects

## Examples
- Example file: https://figshare.com/ndownloader/files/33982973

## Notes
- https://jvalue.github.io/jayvee/docs/user/block-types/HttpExtractor
- https://jvalue.github.io/jayvee/docs/dev/intro

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by A-M-A-X** [comment]
I used the [follow-redirects](https://www.npmjs.com/package/follow-redirects) npm package in combination with the respective types. The default max. number of redirects is 21. Should I make this property available to the jayvee user or should we stick to the default value?  @rhazn

**Comment by rhazn** [comment]
We can stick with the default value.
