### ISSUE TITLE
[FEATURE] E2E tests

### ISSUE THREAD

**Issue by f3l1x98** [jvalue/jayvee#419]
## User Story
1. As a {developer}
2. I want {to have tests to ensure that my new code does not break any existing code (without my knowledge)}
3. So that {I can publish better code}

## User Acceptance Criteria
- [ ] Implement a few End-to-End tests

## Examples
https://github.com/jvalue/jayvee/blob/main/apps/interpreter/src/examples-smoke-test.spec.ts

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
I think the smoke tests are sufficient for now.
