### ISSUE TITLE
Duplicate Logger: DefaultLogger and TestLogger

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/jayvee#430]
The `DefaultLogger` is located in `interpreter-lib`, leading to in dependency cycle. We should move the `DefaultLogger` somewhere else and remove the `TestLogger` once usable.

_Originally posted by @georg-schwarz in https://github.com/jvalue/jayvee/pull/428#discussion_r1307025553_

**Comment by f3l1x98** [comment]
@georg-schwarz I just thought of a potential use case for a dedicated test logger:
The execution implementations rarely "crash" but rather just log warnings etc, so I thought we could extend the test logger to keep a "cache" of logged messages. This would allow tests to check whether certain errors were logged etc.

We could also add an additional option to only write messages to the cache which could reduce logging output in the github actions.
