### ISSUE TITLE
[BUG] Fix wording of value types in documentation

### ISSUE THREAD

**Issue by dirkriehle** [jvalue/jayvee#454]
## Problem

The documentation uses inconsistent forms for the concept of value type. There is "value type", "Valuetype", "valuetype", etc.

## Solution

Settle on the use of "value type" and capitalize the V in "value" only if English grammar requires it.

In implementation or code, turn the space between "value" and "type" into camel case, i.e. "ValueType".

**Comment by dirkriehle** [comment]
Comments welcome; I can try my hands at fixing it in the user documentation.

**Comment by rhazn** [comment]
I agree, would be happy with a PR.

**Comment by georg-schwarz** [comment]
**Hint:** the docs are located as markdown files here: https://github.com/jvalue/jayvee/tree/main/apps%2Fdocs%2Fdocs

**Comment by dirkriehle** [comment]
Sure, will do.
