### ISSUE TITLE
[BUG] <Mathematical operators and long text not allowed in column headers>

### ISSUE THREAD

**Issue by kreuz1995** [jvalue/jayvee#472]
## Steps to reproduce
Run the below code:

pipeline ThermoElectricMaterialsPipeline {
    block ThermoElectricMaterialsESTMExtractor oftype HttpExtractor {
		url: "https://github.com/KRICT-DATA/SIMD/raw/main/dataset/estm.xlsx";
	}
	block ThermoElectricMaterialsESTMXLSXInterpreter oftype XLSXInterpreter {
	}
    block ThermoElectricMaterialsESTMSheetPicker oftype SheetPicker {
        sheetName: "Sheet1";
	}
    block ThermoElectricMaterialsESTMTableInterpreter oftype TableInterpreter {
        header: true;
		columns: [
            'Formula' oftype text,
            'temperature(K)' oftype text,
            'seebeck_coefficient(<span style="font-family: 맑은 고딕;font-size: 15px;">μ</span><span style="font-family: 맑은 고딕;font-size: 15px;">V/K)</span>' oftype text,
            'electrical_conductivity(S/m)' oftype text,
            'thermal_conductivity(W/mK)' oftype text,
            'power_factor(W/mK<span style="font-family: 맑은 고딕;font-size: 15px;">2</span><span style="font-family: 맑은 고딕;font-size: 15px;">)</span>' oftype text,
            'ZT' oftype text,
            'reference' oftype text,
		];
	}
    block ThermoElectricMaterialsESTMDatabaseLoader oftype SQLiteLoader {
        table: "ESTM";
		file: "./ThermoElectricMaterialsDatabase.sqlite";
	}
    ThermoElectricMaterialsESTMExtractor
        -> ThermoElectricMaterialsESTMXLSXInterpreter
        -> ThermoElectricMaterialsESTMSheetPicker
        -> ThermoElectricMaterialsESTMTableInterpreter
        -> ThermoElectricMaterialsESTMDatabaseLoader;
}

## Description
- Expected: All the columns of the dataset shall be present in the exported SQLite database.
- Actual: Columns 'seebeck_coefficient' and   'power_factor' will not be in the exported SQLite tables.

**Comment by rhazn** [comment]
Hi, could you add an example to reproduce this? Copy and pasting the SWC data pipeline you encountered this in would be enough :).

**Comment by rhazn** [comment]
Works for me.
