### ISSUE TITLE
[FEATURE]: Update the docs with information about updating Jayvee and extensions

### ISSUE THREAD

**Issue by OmarFourati** [jvalue/jayvee#477]
## Actual situation 

Updating Jayvee actually not well documented enough that after updating it, some errors may still occur.

## Solution

Update the UI of the documentation to make it clear to update the Jayvee extensions as well, to make sure the user is aware of that.

**Comment by rhazn** [comment]
done with https://github.com/jvalue/jayvee/pull/480
