### ISSUE TITLE
[BUG] Composite Blocktype Validation does not account for different block ordering

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/jayvee#497]
## Steps to reproduce
1. Add an unused block to an existing blocktype definition
2. Move the unused block up and down 

## Description
- Expected: The "unused" warning stays at the unused block
- Actual: The warning jumps over to other blocks

## Notes
- Issue is probably the validation function that assumes the correct order of blocks instead of navigating over the graph of blocks and pipes (see [here](https://github.com/jvalue/jayvee/blob/faecf34f8c2f71dd2fd22483bb916b31190eb58c/libs/language-server/src/lib/validation/checks/block-definition.ts#L81))
- In the same go, the validation logic should be moved to the container (pipeline, composite blocktype) to avoid "going upwards" in the AST as much as possible

**Comment by TungstnBallon** [comment]
This seems to be fixed, perhaps by a44a73c?

[Screencast from 2024-05-17 12-06-38.webm](https://github.com/jvalue/jayvee/assets/59221538/e5a707a9-72c7-42f9-9fe2-f66356a9cc3f)

**Comment by rhazn** [comment]
I agree, can't reproduce either.
