### ISSUE TITLE
[FEATURE] Create screencast on the demo files / tutorial files

### ISSUE THREAD

**Issue by tordans** [jvalue/jayvee#507]
## User Story
1. As a user new to this software and the overall concept
2. I want learn the overall concepts of the software without reading a lot of documentation or investing time by running my own tests
3. So that evaluate if the software is relevant for my use cases, will potentially solve my problems, easy to learn and in conclusion a good fit for me to invest more time in

## Examples
https://www.youtube.com/watch?v=tzPL0yhLBTw – but it does not have to be that polished, a simple talk and code would be great

**Comment by georg-schwarz** [comment]
Hey, thanks for your feedback!

We have a recording of an introduction to Jayvee on YouTube: https://www.youtube.com/watch?v=X8fOK8JIBZA

Unfortunately, the syntax changed at a few points, so the video might already be a little outdated. The project is still moving fast and breaking things, so keeping such material up to date is quite hard :)
Once we have new version of the recording, I will link it in the README!

We would appreciate your feedback if such a video is what you would expect or if you would want more of a hands-on tutorial like the video you linked,

**Comment by tordans** [comment]
Thanks @georg-schwarz that was a great way to get to know the project and form an opinion.

> We would appreciate your feedback if such a video is what you would expect or if you would want more of a hands-on tutorial like the video you linked.

Personally, I prefer the hands on style. It tells a story "I have this problem and that is how I solve it with _tool_". It also allows to explain special things about a tool while showing the example "we do _x_ and see a list of currencies. But we want only two kings, so we need a filter-thing which is _y_ in our _tool_ and voila the list is filtered…".

The presentation style you have in your video was also helpful but all the text that was more or less a copy of the docs on the left where too much to parse while following your talk. So it's not really needed IMO; I will always read the docs for details.

To me, those videos are to get an idea on what this is and how it is supposed to work in a broader sense.

**Comment by georg-schwarz** [comment]
Thanks a lot for sharing your thoughts with us! We will definitely incorporate your feedback in the next video we will record.
