### ISSUE TITLE
[FEATURE] Support invalid / empty integer values

### ISSUE THREAD

**Issue by kreisligaspieler** [jvalue/jayvee#513]
## User Story
1. As a user
2. I want to import rows with empty cells into a database
3. So that i can have empty values not only in text columns, but also in integer columns

## User Acceptance Criteria
- [ ] By default rows whit empty values in integer columns are dropped. It would be better if the user could choose between dropping columns or assigning a "Null"-Value.

## Examples
https://download-data.deutschebahn.com/static/datasets/haltestellen/D_Bahnhof_2020_alle.CSV
->  "Betreiber_Nr" is sometimes empty, so at them moment the corresponding rows are skipped during the import. A solution would be to change the definition of integer or to allow something like that: "Betreiber_Nr" oftypeype integer | undefined

**Comment by georg-schwarz** [comment]
Will be incorporated in https://github.com/jvalue/jayvee/issues/291
