### ISSUE TITLE
[BUG] Formatter loops sometimes

### ISSUE THREAD

**Issue by TungstnBallon** [jvalue/jayvee#589]
## Steps to reproduce
1. Open [`YieldStrengthAndGrainSizeModel.jv`](https://github.com/jvalue/SWC2-JValue-OCDE-Case1/blob/aa64a29e89a412daaa67355d39d39bdc2f13cca0/models/14946186/YieldStrengthAndGrainSizeModel.jv) in VS-Code with the jayvee extension >=v0.5.0-alpha enabled.
2. go to line 28
3. repeatedly press `CTRL` + `SHIFT` +  `I`

## Description
- Expected: The formatter changes the code once
- Actual: The formatter inserts and removes a newline

[format_loop.webm](https://github.com/jvalue/jayvee/assets/59221538/78f56908-0d32-467c-9938-3b3a00e12652)

**Comment by TungstnBallon** [comment]
Yes! I upgraded langium with `npm install --save langium@latest langium-cli@latest`, rebuilt the vs-code-extension and now it works

**Comment by georg-schwarz** [comment]
Should be fixed by the Langium upgrade
