### ISSUE TITLE
[FEATURE] Imports from Anywhere on the FS

### ISSUE THREAD

**Issue by georg-schwarz** [jvalue/jayvee#593]
## User Story
1. As a {Jayvee user}
2. I want {to perform Imports from anywhere of my file system}
3. So that {model parsing and interpretation don't depend on the current directory (like in Python)}

## User Acceptance Criteria
- [ ] Imported documents are dynamically added to the LSP instead of being restricted to a fixed working directory.

See discussion in #590 for more details.

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
Gave it a try to dynamically load files when imported on this branch: https://github.com/jvalue/jayvee/compare/dynamically-load-imported-documents?expand=1

Ran into a roadblock because Langium's [ScopeProvider](https://github.com/eclipse-langium/langium/blob/main/packages/langium/src/references/scope-provider.ts) has a synchronous interface. I will open a ticket to determine whether they would be able to make that async in future releases.

**Comment by georg-schwarz** [comment]
Was pointed to this discussion: https://github.com/eclipse-langium/langium/discussions/1308
We should be able to implement it in that way I think.

**Comment by rhazn** [comment]
FYI, with Jayvee 0.6.0, importing documents above a model still shows an error in the VSCode extension, e.g. consider the following directories:

```
a/model.jv
b/shared.jv
```

If you open `model.jv` in VSCode, it will show the `Import from "./../b/shared.jv" could be resolved. Check if the file exists in the given location.`

```
use {
	Something,
} from "./../b/shared.jv";
```

If you run `model.jv` from `a`, it errors. If you run `a/model.jv` from the root dir, it works. Not sure if I should create a new bug for this or if it is part of this PR @georg-schwarz ?

**Comment by rhazn** [comment]
Actually, the language server part of this might have been a caching (?) issue on my side, seems to work now and not show an error in the jv model. However, the interpreter still errors if run from `a`.
