### ISSUE TITLE
[BUG] The vscode extension cannnot find

### ISSUE THREAD

**Issue by behroozbc** [jvalue/jayvee#627]
## Steps to reproduce
1. I cannot find the vscode extension from the vscode search, the queries was 'jv','*.jv' and 'Jayvee'.

![image](https://github.com/user-attachments/assets/593f66a5-576d-46e3-b610-391ca2c2dc6e)

**Comment by georg-schwarz** [comment]
Yes, we don't publish our extension yet in the VSCode Extension store.
Please install from release by downloading the `vsix` file from here:
https://github.com/jvalue/jayvee/releases

**Comment by behroozbc** [comment]
Is possible to help you with publishing it on the Vscode store?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
