### ISSUE TITLE
Research: Transformations

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#65]
- Research how other solutions handle transformations
  - Are there categories of transformations we can define? e.g. transformations typical for data cleaning or data analytics? -> We could focus on the ones for data cleaning, not as much on data analytics
  - What syntax is used to describe these transformations

**Comment by georg-schwarz** [comment]
@rhazn do we still need this issue?

**Comment by rhazn** [comment]
No I think this is probably done for now with the implemented transformations.
