### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by rhazn** [jvalue/jayvee#98]
## User Story
1. As a {student}
2. I want {to have a handout to learn jayvee}
3. So that {I can develop with it}

## User Acceptance Criteria
- [x] Write user docs for jayvee
- [x] Docs are versioned with code (e.g. as markdown files)
- [ ] Docs are self-sufficient so they can be exported as PDF and given out to students without further context

## Definitions of Done
- [ ] A PR has been opened and accepted
- [ ] All user acceptance criteria are met
- [ ] All tests are passing

**Comment by georg-schwarz** [comment]
What else should be documented for users? Current state at https://jvalue.github.io/jvalue

**Comment by rhazn** [comment]
I think only the tbd for developer docs should be added as new task. But that can be done in a different milestone. I'd close this issue as done.

**Comment by rhazn** [comment]
Being able to export these would be great though for offline experiments. However, there seem to be some projects that allow exporting docusaurus docs into pdf. So I am happy with just keeping everything in docusaurus and when we actually need a PDF we export it, does that sound okay?

**Comment by georg-schwarz** [comment]
Sounds good! In the end they are markdown files displayed as HTML. I'd assume there is plenty of tooling to export as PDF, we just have to filter a good one ^^

Another option for offline experiments would be to start the docs server locally for local browsing. Not sure how important it is having it in a written form?
